# .streamlit/secrets.toml

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1Fm2Zpl9AqDcRyGOlj3KRM4gFi-xw41yvOzeJ5q61ugc/edit?gid=0#gid=0"
worksheet = "Sheet1"

type = "service_account"
project_id = "war-metaphor-survey"
private_key_id = "25a7d1cba29381a5e1be5f8a0a13387dfd33b9e0"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCsiOC8euZFFDAa
2YIRaW3sGJQbyeQWdv1eirhcArPEIGrXyWFnMfG+ldcUHMStA/StFvvRZRBpBwJW
yf2DJ4tBarkgn7hRSSkVmdbF1aI4P2ucWm4DWAxqQ0DFUU83HaB2OljvcDvG1kBh
WTezXDdOlFjhFft9TENaYQoBa2IxgZGUO9HhWBPT+r0idBUIPI/S7EFCPav/W2r5
W+woYdheMvkqzD6xEPxfPcPh+Bc1Ang7takQs3tsjZhC7sEBSsyAosEoNsWCGKEX
CvT8GXgMS5RwSIDNpAyjUo83FjA8xXPBuhIm/M3AWsZwZk4GeABRuppBmeU+NY5N
yJC7CgYrAgMBAAECggEAKJwRFZvxzimZxwASIsoHcu44EjBbbMQ2D8Yj7Zg/OrcM
ntzJ/dGeHmdDV/sLedO4B/Okct1QVwAs10O01WV92/hkOZ8OcaeAMZLjn+4QQCAB
UqxgP44+YdaRjL/+HrFs/tbt7vGiSENOpPssZp2acPbu0o/rgUrtgXzcr4fYdWEw
XB7TbMdeQSGUtE8dlo/rgEVWfSWmDolIUhdSxtTgEqCTPnmtWJfLJJ0ADEQsxPv2
glmzEljN2up3Q/BlzEpdZacX2PLY5ryE7Qyd03VHTyJXzot9wwhj1jZd6o6A1Iae
TjOx3Z1r8cEBUL+J9q3uXATEfoFkJE2OOs5ecC9tCQKBgQDbtGAtJyp8LiMSOgX1
6g+JwnHVgBjdqTr2I5ydjMwFmz/UNw9QaqoRGBcKNkPCN3UfaYvAYvf4PXqQgrbH
uzU2KvWrg9Ww9X6AxXpIerQM1+J3tKIsFCP+UunMdSFJRsD3cHC9/WwCOgKmzBki
wzyF3HsUIO70kr0y3bAaB+HoowKBgQDJCZ5URMP73LYSaxnXS9Kf8le9T5R8FYep
DDiPEmrqixxFZ4/keHxyxLSEl7YB8SJx0UW5lCbmsHE73zEy28BwWsvNtN0v1vx2
aJ/aVXLQxed/z/dp1Y2Vb6oJ4XC+Hjaw5XRgnMlA1pgy/yh40eaU1of7PYWH0E9M
Yz+q3B4c2QKBgHPjZCvNEfrotzUhCA3cBZAr0bHFXNhnMKOuyyjLoL6AUp3U4S4Q
5V4Y7+ZCE2G5sPz9xmqXiacWfrUFTfZyyDGnXWi4JJqwE6dHAyaCGsD/iwSLclN/
2DCJeauQSRuGx7h9RerhZvyRrt5eoA+XHjCZyQ4oBQNa95OCHibM65uzAoGABXHk
PuYJ5NVqfP83mPQtxTU8GR2BqQawQOzaz00xZh7UajDO3eJBhJ49QWYWgOD2DN0d
JVSU5SScPIHkBDudb62V3YFriDMrbU2SHsi3rl3d0kFgsxYcmpKGqXPYqN2Kn6nn
SAKXFNF7F85/Wx5cP2W8Exrsdew3aZs6izcg/akCgYA9qVvszFgud4O3pdHNU5Jy
2z27qova8gvYoHUs6ipYWHejKugqtKN9gnqzfxeFycaDTXk9e8QfvBjSRKSV0L9y
0xcuLirqCFcfkoe4zFNAZ594HXImsvyAc5YSFlXPkdftXgMsdp+ufwcNVSYLKu35
k9zZ4w5y8H7/aowCRSSmYQ==
-----END PRIVATE KEY-----"""
client_email = "survey-bot@war-metaphor-survey.iam.gserviceaccount.com"
client_id = "113583460753526205218"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/survey-bot%40war-metaphor-survey.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
